#!bash
#
# bash completion support for symfony2 console
#
# Copyright (C) 2011 Matthieu Bontemps <matthieu@knplabs.com>
# Distributed under the GNU General Public License, version 2.0.

_imi-conrun()
{
    local cur prev opts cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cmd="${COMP_WORDS[0]}"

    # Load conrun help into help variable
    help=$($cmd)

    # Strip everything up to "Available commands:"
    help=${help/*Available commands:/}

    # Iterate over lines
    POSSIBLE=()
    while read command help; do
        # skip section headers
        if [[ $command =~ ":" ]]; then
                POSSIBLE+=("$command")
        fi
    done <<< "$help"

    possible=${POSSIBLE[@]}
    COMPREPLY=( $(compgen -W "${possible}" -- ${cur}) )
    return 0
}

complete -F _imi-conrun imi-conrun.phar
complete -F _imi-conrun imi-conrun
complete -F _imi-conrun conrun
COMP_WORDBREAKS=${COMP_WORDBREAKS//:}
